export const LOGIN = "LOGIN";
export const LOGIN_ANONYMOUS = "LOGIN_ANONYMOUS";
export const LOGOUT = "LOGOUT";
export const SET_SFW_SESSION = "SET_SFW_SESSION";

export const NEW_SEARCH_RESULTS = "NEW_SEARCH_RESULTS";
export const NEW_SEARCH_QUERY = "NEW_SEARCH_QUERY";

export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const DISMISS_NOTIFICATION = "DISMISS_NOTIFICATION";

export const REDIRECT = "REDIRECT";
export const SET_SHOULD_REFRESH = "SET_SHOULD_REFRESH";

export const SET_FILE_UPLOADED = "SET_FILE_UPLOADED";

export const SET_SPEED_TAGGING = "SET_SPEED_TAGGING";
export const TOGGLE_SPEED_TAGGING_ITEM = "TOGGLE_SPEED_TAGGING_ITEM";
export const CLEAR_SPEED_TAGGING_ITEMS = "CLEAR_SPEED_TAGGING_ITEMS";
